version: "3.8"

services:

  app-5001:
    image: leader-docker:latest
    container_name: node-5001
    ports:
      - "5001:5001"
    environment:
      PORT: "5001"
      OTHER_NODES: "app-5002:5002,app-5003:5003"

  app-5002:
    image: leader-docker:latest
    container_name: node-5002
    ports:
      - "5002:5002"
    environment:
      PORT: "5002"
      OTHER_NODES: "app-5001:5001,app-5003:5003"

  app-5003:
    image: leader-docker:latest
    container_name: node-5003
    ports:
      - "5003:5003"
    environment:
      PORT: "5003"
      OTHER_NODES: "app-5001:5001,app-5002:5002"