version: "3.8"

services:
  app-5001:
    image: leader-docker:latest
    container_name: node-5001
    ports:
      - "5001:5001"
    environment:
      PORT: "5001"
      ALL_PORTS: "5001,5002,5003,5004,5005"

  app-5002:
    image: leader-docker:latest
    container_name: node-5002
    ports:
      - "5002:5002"
    environment:
      PORT: "5002"
      ALL_PORTS: "5001,5002,5003,5004,5005"

  app-5003:
    image: leader-docker:latest
    container_name: node-5003
    ports:
      - "5003:5003"
    environment:
      PORT: "5003"
      ALL_PORTS: "5001,5002,5003,5004,5005"

  app-5004:
    image: leader-docker:latest
    container_name: node-5004
    ports:
      - "5004:5004"
    environment:
      PORT: "5004"
      ALL_PORTS: "5001,5002,5003,5004,5005"

  app-5005:
    image: leader-docker:latest
    container_name: node-5005
    ports:
      - "5005:5005"
    environment:
      PORT: "5005"
      ALL_PORTS: "5001,5002,5003,5004,5005"