version: "3.8"

services:

  resource:
    image: mutex_resource:latest
    container_name: resource
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"

  app-5001:
    image: mutex:latest
    container_name: node-5001
    ports:
      - "5001:5001"
    environment:
      PORT: "5001"
      RESOURCE_ADDR: "resource:5000"
      NEXT_NODE: "5002"

  app-5002:
    image: mutex:latest
    container_name: node-5002
    ports:
      - "5002:5002"
    environment:
      PORT: "5002"
      RESOURCE_ADDR: "resource:5000"
      NEXT_NODE: "5003"

  app-5003:
    image: mutex:latest
    container_name: node-5003
    ports:
      - "5003:5003"
    environment:
      PORT: "5003"
      RESOURCE_ADDR: "resource:5000"
      NEXT_NODE: "5001"